"""initial schema

Revision ID: 1c2a24ce75f0
Revises:
Create Date: 2026-07-22 21:39:04.765456

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c2a24ce75f0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "films",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("letterboxd_title", sa.String(), nullable=False),
        sa.Column("letterboxd_year", sa.Integer(), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("tmdb_title", sa.String(), nullable=True),
        sa.Column("tmdb_year", sa.Integer(), nullable=True),
        sa.Column("tmdb_release_date", sa.String(), nullable=True),
        sa.Column("poster_path", sa.String(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("vote_average", sa.Float(), nullable=True),
        sa.Column("match_confidence", sa.String(), nullable=True),
        sa.Column("year_mismatch", sa.Boolean(), nullable=True),
        sa.Column("date_added", sa.DateTime(), nullable=False),
        sa.Column("watched", sa.Boolean(), nullable=True),
        sa.Column("watched_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("last_checked", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("films", schema=None) as batch_op:
        batch_op.create_index(
            "idx_films_title_year", ["letterboxd_title", "letterboxd_year"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_films_last_checked"), ["last_checked"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_films_letterboxd_title"), ["letterboxd_title"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_films_tmdb_id"), ["tmdb_id"], unique=True)

    op.create_table(
        "streaming_offers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("country_name", sa.String(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("provider_name", sa.String(), nullable=False),
        sa.Column("monetization_type", sa.String(), nullable=False),
        sa.Column("streaming_url", sa.Text(), nullable=True),
        sa.Column("logo_path", sa.String(), nullable=True),
        sa.Column("display_priority", sa.Integer(), nullable=True),
        sa.Column("checked_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["film_id"], ["films.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("streaming_offers", schema=None) as batch_op:
        batch_op.create_index("idx_offers_checked_at", ["checked_at"], unique=False)
        batch_op.create_index(
            "idx_offers_country_provider", ["country_code", "provider_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_streaming_offers_film_id"), ["film_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_streaming_offers_provider_name"), ["provider_name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("streaming_offers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_streaming_offers_provider_name"))
        batch_op.drop_index(batch_op.f("ix_streaming_offers_film_id"))
        batch_op.drop_index("idx_offers_country_provider")
        batch_op.drop_index("idx_offers_checked_at")

    op.drop_table("streaming_offers")
    with op.batch_alter_table("films", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_films_tmdb_id"))
        batch_op.drop_index(batch_op.f("ix_films_letterboxd_title"))
        batch_op.drop_index(batch_op.f("ix_films_last_checked"))
        batch_op.drop_index("idx_films_title_year")

    op.drop_table("films")
    # ### end Alembic commands ###
